### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by ainthek** [m1k1o/shop-search#3]
$ npm test

> shop-search@1.0.0 test C:\workspaces\shop-search
> mocha --colors

  shopSearch: getOffer
    √ getOffer is working as expected (130ms)

  shopSearch: getOffers
    √ getOffers is working as expected with Object (429ms)
    √ getOffers is working as expected with Array too (334ms)
    √ getOffers fails on 404

  shopSearch: sortProducts
    1) sortProducts gets cheapest product
    2) reversed sortProducts gets most expensive product
    √ sortProducts does not fail on junk data
    3) sortProducts works with array too

  shopSearch: parsePrice
    √ parsePrice works correctly with commas
    √ parsePrice ignored dots

  7 passing (909ms)
  3 failing

  1) shopSearch: sortProducts
       sortProducts gets cheapest product:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  name: 'Liquid iPhone 7/8 light blue ROZBALENÉ',
  price: 9.8,
  shop: 'okay',
  url: 'https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/'
}

should equal

{
  name: 'Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ',
  price: 9.8,
  shop: 'okay',
  url: 'https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/'
}
      + expected - actual

       {
      -  "name": "Liquid iPhone 7/8 light blue ROZBALENÉ"
      +  "name": "Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ"
         "price": 9.8
         "shop": "okay"
      -  "url": "https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/"
      +  "url": "https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/"
       }

      at Context.<anonymous> (test\index.spec.js:83:16)

  2) shopSearch: sortProducts
       reversed sortProducts gets most expensive product:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  name: 'Apple iPhone Xs Max, 512GB, Zlatý',
  price: 1679,
  shop: 'mall',
  url: 'https://www.mall.sk/apple-iphone/apple-iphone-xs-max-512gb-zlaty'
}

should equal

{
  name: 'Apple iPhone Xs Max, 512GB, Vesmírne šedý',
  price: 1679,
  shop: 'mall',
  url: 'https://www.mall.sk/apple-iphone/apple-iphone-xs-max-512gb-vesmirne-sedy'
}
      + expected - actual

       {
      -  "name": "Apple iPhone Xs Max, 512GB, Zlatý"
      +  "name": "Apple iPhone Xs Max, 512GB, Vesmírne šedý"
         "price": 1679
         "shop": "mall"
      -  "url": "https://www.mall.sk/apple-iphone/apple-iphone-xs-max-512gb-zlaty"
      +  "url": "https://www.mall.sk/apple-iphone/apple-iphone-xs-max-512gb-vesmirne-sedy"
       }

      at Context.<anonymous> (test\index.spec.js:95:16)

  3) shopSearch: sortProducts
       sortProducts works with array too:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  name: 'Liquid iPhone 7/8 light blue ROZBALENÉ',
  price: 9.8,
  shop: '0',
  url: 'https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/'
}

should equal

{
  name: 'Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ',
  price: 9.8,
  shop: '0',
  url: 'https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/'
}
      + expected - actual

       {
      -  "name": "Liquid iPhone 7/8 light blue ROZBALENÉ"
      +  "name": "Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ"
         "price": 9.8
         "shop": "0"
      -  "url": "https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/"
      +  "url": "https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/"
       }

      at Context.<anonymous> (test\index.spec.js:115:16)

npm ERR! Test failed.  See above for more details.

**Comment by m1k1o** [comment]
When the price is same, what condition should be used to determine order? Name?

**Comment by m1k1o** [comment]
Let's assume, we're only interested in price, so we need to test only that field.

```js
assert.deepEqual(offers[0].price, 1679)
```

**Comment by ainthek** [comment]
Still faling:     1) sortProducts works with array too

  shopSearch: parsePrice
    √ parsePrice works correctly with commas
    √ parsePrice ignored dots


  9 passing (813ms)
  1 failing

  1) shopSearch: sortProducts
       sortProducts works with array too:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  name: 'Liquid iPhone 7/8 light blue ROZBALENÉ',
  price: 9.8,
  shop: '0',
  url: 'https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/'
}

should equal

{
  name: 'Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ',
  price: 9.8,
  shop: '0',
  url: 'https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/'
}
      + expected - actual

       {
      -  "name": "Liquid iPhone 7/8 light blue ROZBALENÉ"
      +  "name": "Pouzdro Col Fr iPhone 7/8 red ROZBALENÉ"
         "price": 9.8
         "shop": "0"
      -  "url": "https://www.okay.sk/liquid-iphone-7-8-light-blue-rozbalene/"
      +  "url": "https://www.okay.sk/pouzdro-col-fr-iphone-7-8-red-rozbalene/"
       }

      at Context.<anonymous> (test\index.spec.js:101:16)



npm ERR! Test failed.  See above for more details.

**Comment by m1k1o** [comment]
for god's sake my head hurts so much i forgot that.
